### ISSUE TITLE
Unnamed snapshots after switching apps

### ISSUE THREAD

**Issue by Hefaistos68** [ContextKeeper/ContextKeeper.VisualStudio#1]
So everytime I switch apps, like when debugging and then come back to VS (2017 in this case) I get a new snapshot with the current open files, without a name.
![context keeper 001](https://user-images.githubusercontent.com/8855055/158362836-c9a99ae8-5c99-4342-801d-3ed6d26362bc.jpg)
![context keeper 002](https://user-images.githubusercontent.com/8855055/158362852-df56c228-3b6a-4d43-9e8b-c0ad594b50e3.jpg)

Actually its not every time I switch, but often. Not sure yet what triggers it.

Here is the output log from the very first beginning after installation:

10:16:41.583: [ProcessId:656] [ThreadId:1] Info [Create] Version: 1.5.8106.38008 Release 'VS 2015+ build' (compiled: 12/03/2022 21:06:56)
10:16:41.583: [ProcessId:656] [ThreadId:1] Info [Init] Visual Studio version: 15.0
10:16:41.815: [ProcessId:656] [ThreadId:1] Info [StartListeningForBranchChanges] No Git branch detected.
10:16:41.830: [ProcessId:656] [ThreadId:1] Info [InitWindowEventsHandlers] Handlers for window events hook up.
10:16:42.001: [ProcessId:656] [ThreadId:1] Info [LoadSnapshots] Loading mental snapshots ...
10:16:42.016: [ProcessId:656] [ThreadId:1] Info [LoadSnapshots] Snapshots loaded.
10:16:48.022: [ProcessId:656] [ThreadId:1] Info [CreateCommandHandler] Creating snapshot ...
10:16:48.230: [ProcessId:656] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\TFS-AS\UPCI\AAC\2-Development\PR006108.1\Source\.contextkeeper\snapshot 1.ck
10:16:48.244: [ProcessId:656] [ThreadId:1] Info [CreateCommandHandler] Snapshot 'snapshot 1' created.
10:16:55.940: [ProcessId:656] [ThreadId:11] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:16:55.941: [ProcessId:656] [ThreadId:11] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:16:58.646: [ProcessId:656] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\TFS-AS\UPCI\AAC\2-Development\PR006108.1\Source\.contextkeeper\snapshot.ck
10:17:26.566: [ProcessId:656] [ThreadId:30] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:17:26.566: [ProcessId:656] [ThreadId:30] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:17:36.642: [ProcessId:656] [ThreadId:1] Info [Restore] Finished in 0.90 seconds.
10:17:36.658: [ProcessId:656] [ThreadId:19] Info [LoadSelectedItemModelCommandHandler] 'snapshot' snapshot restored.
10:17:45.197: [ProcessId:656] [ThreadId:1] Info [Restore] Finished in 0.50 seconds.
10:17:45.197: [ProcessId:656] [ThreadId:8] Info [LoadSelectedItemModelCommandHandler] 'snapshot' snapshot restored.
10:18:00.206: [ProcessId:656] [ThreadId:7] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:18:00.206: [ProcessId:656] [ThreadId:7] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:23:36.049: [ProcessId:656] [ThreadId:1] Info [Restore] Finished in 0.44 seconds.
10:23:36.049: [ProcessId:656] [ThreadId:31] Info [LoadSelectedItemModelCommandHandler] 'snapshot' snapshot restored.
10:24:09.609: [ProcessId:656] [ThreadId:20] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:24:09.609: [ProcessId:656] [ThreadId:20] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:24:27.493: [ProcessId:656] [ThreadId:1] Info [Restore] Finished in 0.50 seconds.
10:24:27.493: [ProcessId:656] [ThreadId:30] Info [LoadSelectedItemModelCommandHandler] 'snapshot' snapshot restored.
10:24:37.024: [ProcessId:656] [ThreadId:1] Info [ContextMenuServiceOnUpdateCommandFired] Updating snapshot '' ...
10:24:37.040: [ProcessId:656] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\TFS-AS\UPCI\AAC\2-Development\PR006108.1\Source\.contextkeeper\.ck
10:24:37.055: [ProcessId:656] [ThreadId:1] Info [ContextMenuServiceOnUpdateCommandFired] Snapshot '' updated.
10:24:56.406: [ProcessId:656] [ThreadId:315] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:24:56.406: [ProcessId:656] [ThreadId:315] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:29:36.982: [ProcessId:656] [ThreadId:331] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:29:36.982: [ProcessId:656] [ThreadId:331] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:30:24.421: [ProcessId:656] [ThreadId:24] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:30:24.436: [ProcessId:656] [ThreadId:24] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:33:02.889: [ProcessId:656] [ThreadId:30] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:33:02.905: [ProcessId:656] [ThreadId:30] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:34:00.233: [ProcessId:656] [ThreadId:333] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:34:00.233: [ProcessId:656] [ThreadId:333] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:34:31.749: [ProcessId:656] [ThreadId:31] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:34:31.749: [ProcessId:656] [ThreadId:31] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:42:21.378: [ProcessId:656] [ThreadId:23] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:42:21.378: [ProcessId:656] [ThreadId:23] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:43:24.010: [ProcessId:656] [ThreadId:332] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:43:24.010: [ProcessId:656] [ThreadId:332] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:43:51.463: [ProcessId:656] [ThreadId:20] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:43:51.479: [ProcessId:656] [ThreadId:20] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:45:09.085: [ProcessId:656] [ThreadId:329] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:45:09.085: [ProcessId:656] [ThreadId:329] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:58:12.500: [ProcessId:656] [ThreadId:331] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:58:12.500: [ProcessId:656] [ThreadId:331] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:58:27.782: [ProcessId:656] [ThreadId:59] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:58:27.782: [ProcessId:656] [ThreadId:59] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:58:55.352: [ProcessId:656] [ThreadId:315] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:58:55.352: [ProcessId:656] [ThreadId:315] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
10:59:13.024: [ProcessId:656] [ThreadId:31] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
10:59:13.024: [ProcessId:656] [ThreadId:31] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.
11:00:33.198: [ProcessId:656] [ThreadId:43] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
11:00:33.198: [ProcessId:656] [ThreadId:43] Info [SaveSnapshotTimerElapsed] Snapshot auto-saved.

**Comment by PiotrKarczmarz** [comment]
Thanks for reporting the issue and including the log file. I've successfully reproduced it and it's now fixed in [version 1.6.25](https://contextkeeper.io/blog/downloads/#v1.6)

**Comment by Hefaistos68** [comment]
I updated to 1.6.25 but I am still seeing an unnamed snapshot, no GIT, although the solution is on TFS. Might this be the reason?

**Comment by PiotrKarczmarz** [comment]
> I updated to 1.6.25 but I am still seeing an unnamed snapshot, no GIT, although the solution is on TFS. Might this be the reason?

That's interesting. I have tried to cover every possible scenario when it could happen when there is not .git folder detected but probably I've missed something. Could you please add part of the log file were there something along those lines:

`[SaveCurrentBranch] No git branch detected, no snapshot saved.`
`[SaveSnapshotTimerElapsed] Snapshot auto-saved.`

**Comment by Hefaistos68** [comment]
![image](https://user-images.githubusercontent.com/8855055/162207089-ca58fd3d-c307-41cd-8115-fe7962f23b3e.png)


```
13:45:40.276: [ProcessId:3548] [ThreadId:1] Info [Create] Version: 1.6.8126.22360 Release 'VS 2015+ build' (compiled: 01/04/2022 12:25:20)
13:45:40.276: [ProcessId:3548] [ThreadId:1] Info [Init] Visual Studio version: 15.0
13:45:40.495: [ProcessId:3548] [ThreadId:1] Info [InitWindowEventsHandlers] Handlers for window events hook up.
13:45:40.979: [ProcessId:3548] [ThreadId:1] Info [DteEventsOnOnStartupComplete] Startup completed.
13:45:56.315: [ProcessId:3548] [ThreadId:1] Info [StartListeningForBranchChanges] No Git branch detected.
13:45:56.315: [ProcessId:3548] [ThreadId:1] Info [LoadSnapshots] Loading mental snapshots ...
13:45:58.424: [ProcessId:3548] [ThreadId:1] Info [LoadSnapshots] Snapshots loaded.
13:46:12.321: [ProcessId:3548] [ThreadId:1] Info [Restore] Finished in 1.22 seconds.
13:46:12.321: [ProcessId:3548] [ThreadId:23] Info [LoadSelectedItemModelCommandHandler] 'snapshot' snapshot restored.
13:46:27.264: [ProcessId:3548] [ThreadId:21] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
13:46:30.720: [ProcessId:3548] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\redactedpath\Source\.contextkeeper\ML_CE.ck
13:47:32.280: [ProcessId:3548] [ThreadId:22] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
13:47:59.021: [ProcessId:3548] [ThreadId:50] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
13:48:41.594: [ProcessId:3548] [ThreadId:7] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
13:49:05.815: [ProcessId:3548] [ThreadId:7] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
13:49:09.867: [ProcessId:3548] [ThreadId:1] Info [CreateCommandHandler] Creating snapshot ...
13:49:09.892: [ProcessId:3548] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\redactedpath\Source\.contextkeeper\snapshot 2.ck
13:49:09.897: [ProcessId:3548] [ThreadId:1] Info [CreateCommandHandler] Snapshot 'snapshot 2' created.
13:49:20.138: [ProcessId:3548] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\redactedpath\Source\.contextkeeper\ML_CE Context Home.ck
13:55:35.934: [ProcessId:3548] [ThreadId:1] Info [CreateCommandHandler] Creating snapshot ...
13:55:35.952: [ProcessId:3548] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\redactedpath\Source\.contextkeeper\snapshot 3.ck
13:55:35.965: [ProcessId:3548] [ThreadId:1] Info [CreateCommandHandler] Snapshot 'snapshot 3' created.
13:55:55.995: [ProcessId:3548] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\redactedpath\Source\.contextkeeper\ML_CE context.ck
13:56:30.668: [ProcessId:3548] [ThreadId:7] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
13:57:37.109: [ProcessId:3548] [ThreadId:1] Info [CreateCommandHandler] Creating snapshot ...
13:57:37.120: [ProcessId:3548] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\redactedpath\Source\.contextkeeper\snapshot 4.ck
13:57:37.149: [ProcessId:3548] [ThreadId:1] Info [CreateCommandHandler] Snapshot 'snapshot 4' created.
14:04:48.599: [ProcessId:3548] [ThreadId:9] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.
14:06:10.657: [ProcessId:3548] [ThreadId:1] Info [CreateCommandHandler] Creating snapshot ...
14:06:10.669: [ProcessId:3548] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\redactedpath\Source\.contextkeeper\snapshot 5.ck
14:06:10.691: [ProcessId:3548] [ThreadId:1] Info [CreateCommandHandler] Snapshot 'snapshot 5' created.
14:06:32.032: [ProcessId:3548] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\redactedpath\Source\.contextkeeper\ML_CE contextmanager.ck
14:06:37.462: [ProcessId:3548] [ThreadId:1] Info [CreateCommandHandler] Creating snapshot ...
14:06:37.490: [ProcessId:3548] [ThreadId:1] Info [SaveSnapshot] Snapshot saved:E:\redactedpath\Source\.contextkeeper\snapshot 6.ck
14:06:37.505: [ProcessId:3548] [ThreadId:1] Info [CreateCommandHandler] Snapshot 'snapshot 6' created.
14:07:02.694: [ProcessId:3548] [ThreadId:61] Info [SaveCurrentBranch] No git branch detected, no snapshot saved.

`

**Comment by PiotrKarczmarz** [comment]
Double checking, is this unnamed snapshot was created after installing v1.6.25?

**Comment by Hefaistos68** [comment]
I just checked and it might have been an old one. Not sure anymore now. I have deleted all snapshots now and try to repro it. Lets see.
